version: '3'

services:

  webapp:
    container_name: app
    depends_on:
      - db
      - jaeger
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./volumes/images:/go/src/gollery/images
    environment:
      - GO_ENV=dev_docker

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gollery

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
