version: "3"

services:
  frontend:
    container_name: frontend
    depends_on:
      - db
      - backend
    restart: always
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=developmentDocker

  backend:
    container_name: backend
    depends_on:
      - db
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./volumes/images:/go/src/gollery/images
    environment:
      - GO_ENV=dev_docker

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gollery
