version: '3'

services:

  webapp:
    container_name: app
    depends_on:
      - db
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./volumes/images:/go/src/gollery/images
    environment:
      - GO_ENV=dev_docker

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gollery
