version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gollery

  webapp:
    container_name: app
    depends_on:
      - db
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - GO_ENV=dev_docker
